version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13-buster
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            go test -coverprofile=c.out

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: 0 0 * * *
          filters:
            branches:
              only:
                - master
    jobs:
      - build
