version: 2.1
orbs:
  qlty-orb: qltysh/qlty-orb@0.1.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.13-buster
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            go test -coverprofile=c.out
      - qlty-orb/coverage_publish:
          files: c.out
          strip_prefix: github.com/particleflux/sensible-terminal/

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: 0 0 * * *
          filters:
            branches:
              only:
                - master
    jobs:
      - build
